### ISSUE TITLE
Cross Border usage

### ISSUE THREAD

**Issue by ericszimmermann** [DP-3T/dp3t-app-android-ch#107]
I am living near the border to Germany.
Would it be possible to implement a part of the backend of another country to get the validated tested ID's? If this is possible, it would be great for people near the border if you could check the box for neighboring countries to see the corresponding dangers.
You would then only need an app, because I would then have myself tested by my doctor/hospital in Switzerland. If the other countries would offer the same option (to check the databases of the other countries), these people would also be warned in case of a case from me.

**Comment by simonroesch** [comment]
Yes, we are working on this. You can check the details in https://github.com/DP-3T/documents/blob/master/DP3T%20-%20Interoperability%20Decentralized%20Proximity%20Tracing%20Specification%20(Preview).pdf
