### ISSUE TITLE
Please clarify how to whitelist Google account for ExposureNotification

### ISSUE THREAD

**Issue by cowwoc** [DP-3T/dp3t-app-android-ch#127]
The readme says "The app will not be functional unless your Google account is whitelisted for ExposureNotification testing" but does not explain how to actually do this. Can you please provide (or link to) documentation to help end-users figure out how to do so?

**Comment by simonroesch** [comment]
Unfortunately, at the moment this is not yet possible for people outside the official development team of BAG. But this is likely to change in the future to enable more developers. We will update the readme as soon as possible.
