### ISSUE TITLE
17: API: Nearby.EXPOSURE_NOTIFICATION_API is not avaliabe on this device.

### ISSUE THREAD

**Issue by Khyta** [DP-3T/dp3t-app-android-ch#135]
Hello there.
I wanted to install the SwissCovid app on my Honor 6x (Android 8.0.0, EMUI 8.0.0) but I got this Error:
`17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device.` and below:
`Connection failed with: ConnectionResult{statusCode=UNKOWN_ERROR_CODE(39501), resolution=null, message=null}`
The Google PlayStore is Version `20.5.19-all [0] [PR] 316024227`
Bluetooth is activated and I tried to reinstall the application. 
Anybody knows what's happening?

**Comment by trembel** [comment]
The `EXPOSURE_NOTIFICATION_API` is pretty new and was published by Google and Apple on 20 May 2020.
Probably you have to update you PlayStore to a newer version.

**Comment by stefanriesen** [comment]
See also #51. What is the version of your Google Play Services (Not PlayStore)?

**Comment by Khyta** [comment]
Google Play Services: 20.21.17 (040408-316502805)
Google Services Framework: 8.0.0-5280164
Google PlayStore has been updated today and it's still not working: 20.5.19-all [0] [PR] 316024227
Android Security Patch Level: 01.01.2020

**Comment by jctian** [comment]
I have the same problem. I tried to install the app on two different phones (Samsung S10 and Oneplus 5, both Android 10), but on S10 the app would return such error whereas on Oneplus it works fine. 

The version of Google Play Services on both devices are exactly the same: `20.21.17(120400-316502805)`

Using the adb command mentioned in [#51](https://github.com/DP-3T/dp3t-app-android-ch/issues/51) gets similar output

Oneplus:  
```
com.google.android.gms.nearby_en [v202304013]
```

Samsung (same line but twice...): 
```
com.google.android.gms.nearby_en [v202304013]
com.google.android.gms.nearby_en [v202304013]
```

**Comment by haonase05189** [comment]
The experts can help me fix the error :
17: APIL Nearby.Exposure _Notification_API is not avaliable on this device 
or someone has run the complete app, guide me

**Comment by simonroesch** [comment]
One more reason for this error could be, that you are trying to run the app as a secondary user. Unfortunately, the ExposureNotification framework of Google only works for the primary (system) user of the device. We will add an explizit error message for this case in a future version.

**Comment by Khyta** [comment]
I didn't know that you could run apps as a secondary user. How do I know, that I am running this app as a secondary user?

**Comment by simonroesch** [comment]
In version [1.0.7](https://github.com/DP-3T/dp3t-app-android-ch/releases/tag/1.0.7) we included a check if the app is running as the primary (system) user and show a corresponding error message. On how to switch users see https://support.google.com/nexus/answer/2865483?hl=en
