### ISSUE TITLE
proximitx tracing remains deactivated

### ISSUE THREAD

**Issue by covuser** [DP-3T/dp3t-app-android-ch#136]
Why?
ios 13.5.1  iphone 6s. bluetooth on. SwissCovid app installed.

ios menu > privacy > bluetooth (/ health) COVID-19 Exposure logging > Off. Not available in your region. ......

note: apple id & handset region is set to switzerland. handy nummer ch.

**Comment by Rosthouse** [comment]
This seems to be an issue with the iOS App, which you can find here: https://github.com/DP-3T/dp3t-app-ios-ch

**Comment by simonroesch** [comment]
Please open a bug on the iOS repository and include screenshots of the settings and the SwissCovid app when you try to activate Exposure logging from the app.
