### ISSUE TITLE
Erroneous translation of a button in French

### ISSUE THREAD

**Issue by cryptopathe** [DP-3T/dp3t-app-android-ch#138]
It should be `"Envoyer"`, not `"Enviar"`.

https://github.com/DP-3T/dp3t-app-android-ch/blob/c626a84fa50bcfed531ee301cd7c5e184869b055/app/src/main/res/values-fr/strings.xml#L23

**Comment by lourkeur** [comment]
Same here, can confirm it shows in-app.
![20200704_150533](https://user-images.githubusercontent.com/15657735/86513124-d96bf180-be07-11ea-9803-a0d2c4a04616.jpg)

**Comment by simonroesch** [comment]
Thank you for the feedback! This has been fixed in our translation management tool and will be fixed with the next release.

**Comment by simonroesch** [comment]
The fix is included in version [1.0.7](https://support.google.com/nexus/answer/2865483?hl=en) that will be released next week.
