### ISSUE TITLE
An unexpected error occurred when synchronising the notifications (AGAEN10.-2)

### ISSUE THREAD

**Issue by imsodin** [DP-3T/dp3t-app-android-ch#140]
The error header is "no current data". I had mobile data disabled yesterday, so I assume the error is due to not having data connectivity. That should be an expected error with a user-friendly warning that the app requires a data connection (or even better: cache announcements for some time and only display a warning about missing data connection if no connection could be established in say the last 12h or something). In addition the error doesn't disappear once connection is regained, I need to manually stop the app and restart it for the error to disappear.

Edit: Turns out it was something completely different: I had the same error again while having data. At the same time I got a system notification about running out of space on the internal partition. Still would be nice if there was a less cryptid/more user friendly error about this.

**Comment by simonroesch** [comment]
Can you please provide a screenshot of the error?

**Comment by imsodin** [comment]
Unfortunately not, as it's gone by now (I'd probably have to fill up my internal storage again :) ). Since it was a general issue with my system not caused by the app, I'll close this. My main motivation for reporting the error was UX: Given the sensitive purpose of this app and the requirement to keep trust by users, I consider cryptic errors potentially problematic. Thus I believe a less cryptic message (if an error really needs to be surfaced) and/or a simple button to report errors would help with that.
