### ISSUE TITLE
Frequent notifications when Bluetooth intentionally turned off

### ISSUE THREAD

**Issue by azurite** [DP-3T/dp3t-app-android-ch#145]
**Issue:**

App version 1.0.5 running on android 10. Whenever Bluetooth is intentionally turned off, when being at home for example, the app sends regular notifications (about 7 per day according to the android app info settings) that Bluetooth needs to be turned on in order for tracing to work. At the moment one can mute notifications from the android settings but I assume this would also mute exposure notifications. It seems to me that these notifications are a little bit too frequent and can be distracting at times.

![photo_2020-07-02_13-07-33](https://user-images.githubusercontent.com/16439305/86351765-0e8c0e80-bc65-11ea-8f02-1b6feec01ce5.jpg)

**Proposed Solution:**

Adding an option to disable such notifications from the app or reducing the frequency to 1 notification per day for example.

**Comment by treysis** [comment]
This is also the case when currently using a different contact tracing app (e.g. Immuni or Corona-Warn-App or StoppCorona). Notifications about inactive tracing should probably limited to 3 or 4 per day (and one time, when a switch is detected).

**Comment by simonroesch** [comment]
This problem has been resolved with version [1.0.7](https://github.com/DP-3T/dp3t-app-android-ch/releases/tag/1.0.7). The notification now only shows up once after disabling bluetooth (after a delay of 5min) and is not shown again until bluetooth is at least once enabled again.
