### ISSUE TITLE
App cannot be used on open source android variants

### ISSUE THREAD

**Issue by janulis** [DP-3T/dp3t-app-android-ch#146]
Hello,

I compiled and installed the app on my phone running a pure Android Open Source Project [(AOSP)](https://source.android.com/) OS. Unfortunately after launching the app it turns out that it has a Google Play Services dependency which is a closed source software and not available in AOSP or Lineage OS.
Is there any solution/workaround for open source android users?

Thanks!

**Comment by rachyandco** [comment]
see issue https://github.com/DP-3T/dp3t-app-android-ch/issues/59
