### ISSUE TITLE
Give information that the system really works by providing some statistics

### ISSUE THREAD

**Issue by Swissbite** [DP-3T/dp3t-app-android-ch#147]
Currently, all you see is tat the app tells you that it is "aktiv". It would be nice to have some information about:
- Last sync from central server
- How many foreign tokens the device has seen **or** local has been saved for yesterday/the last 7 days/14 days

That would help get a sense of how many contacts you have.

A **never do** is:
- Display this data immediately updated. Reason: You might find out if a person next to you is using the app or not.

**Comment by alexiri** [comment]
I think this feature is very important to motivate people to keep the app installed. How do I know it's actually doing something? Have I come into contact with anybody else that is using it? Some sort of feedback that encouraged people to keep it installed would be useful.

**Comment by stefanriesen** [comment]
This Info is already available in Android under Settings/Google/Covid-19 Notifications/Exposure Checks

![Screenshot_20200704-114855~2](https://user-images.githubusercontent.com/66070600/86510002-7c167700-bdec-11ea-8603-d31087a193f3.png)

**Comment by alexiri** [comment]
Interesting, I did not know that was there. Would it be possible for the SwissCovid app to show it, or at least to provide a link to this settings page? That's where I was expecting this info to be.

I'm surprised to see multiple (8-10) checks at exactly the same time with different hashes, I would expect only one per timestamp.

**Comment by simonroesch** [comment]
With version [1.0.7](https://github.com/DP-3T/dp3t-app-android-ch/releases/tag/1.0.7) a new feature was included showing the last successful synchronisation time with the backend.
The Google ExposureNotification API does not provide any possibility for showing the number of registered tokens.
