### ISSUE TITLE
When, in the app, setting up "allow the app to run in background", it doesn't do it 

### ISSUE THREAD

**Issue by maxime129** [DP-3T/dp3t-app-android-ch#151]
Phone: oppo Reno (color os)
Issue: app says to let app run in background, and tell it back 15 min after
Root cause: app has been configured to smart background running
Is it an os limitation? May be pushing a message such as "if that message occurs more than once, you'll have to change it manually in setup > search battery > power saver options" (oppo path...) Would be enough

**Comment by simonroesch** [comment]
We reported this issue to Oppo and they are working on a fix for it that should be available soon.

**Comment by buenzli-ubique** [comment]
Oppo should have fixed this by now, adding an exemption rule for SwissCovid. 

Can you confirm that it's working now as intended @maxime129?
