### ISSUE TITLE
Unexpected error "No current data" (AGAEN39508.-2) 

### ISSUE THREAD

**Issue by hafisch83** [DP-3T/dp3t-app-android-ch#152]
Hello

Sporadically I get an error AGAEN39508.-2 with the message, that no current data are available.

Appended the needed version information

**Phone**: Shift5me
**Android**: 8.0.0
**SwissCovid-App** Version 1.0.5

The following URL shows the error:
[https://drive.google.com/file/d/1mxQ8mLVNh7zmq--PjZhQLWwpIyhI-DWF/view?usp=sharing](url)

**Comment by KlausSchlosser** [comment]
Hello 

Same here. The error appeared after the first insallation of the app. I then deleted and reinstalled it, but the error reappeared. Then about a week ago, it disappeared suddenly, just to reappear yesterday. 
No updates of Android made during this time.

Phone: Samsung A70
Android: 10
App version: 1.0.5 (19.06.)

**Comment by simonroesch** [comment]
This issue is already covered by https://github.com/DP-3T/dp3t-app-android-ch/issues/100
