### ISSUE TITLE
0 keys displayed in "Exposure checks" menu

### ISSUE THREAD

**Issue by simonroesch** [DP-3T/dp3t-app-android-ch#169]
On some Android devices all entries on Settings > Google > COVID-19 Notifications > Exposure checks show "Number of keys: 0" and "Number of matches: 0".
![image](https://user-images.githubusercontent.com/30999902/88082194-b8362f80-cb81-11ea-9065-a5b0ef4f2a30.png)
This is not a bug of the SwissCovid app but of the ExposureNotification framework provided by Google. The bug was reported to Google and will be fixed with a future version of the framework. The behaviour of the app is not affected, the bug only affects the number show in the "Exposure checks" menu, the checks are performed normally with all provided keys.

**Comment by Kariamos** [comment]
Any news with this problem from Google?

**Comment by simonroesch** [comment]
This issue was fixed by Google and should now be available on most devices.
