### ISSUE TITLE
Background Mode seems to be disabled frequently

### ISSUE THREAD

**Issue by redimosi** [DP-3T/dp3t-app-android-ch#170]
On my Xiaomi it looks like the backround mode is disabled frequently. Sometimes it shows me a red error when I open the app, that I need to allow background activity. Not sure it works always as expected, because I need to check that manually. No idea why it comes back, seems to be random, but really frequently (once a day)

**Comment by simonroesch** [comment]
Do you have any battery saver apps installed that might trigger this behaviour? Otherwise you could check if it makes a difference if you go to the Settings > Battery  & performance > Battery optimization > App battery saver search for SwissCovid and select "No restriction".

**Comment by redimosi** [comment]
> Do you have any battery saver apps installed that might trigger this behaviour? Otherwise you could check if it makes a difference if you go to the Settings > Battery & performance > Battery optimization > App battery saver search for SwissCovid and select "No restriction".

already set it to "No restriction" the second time this happened. The funny thing is that since I've opened the issue, it never stops. But perhaps it's because I open the app more frequently to check the status. Will keep try to reproduce. If I'm the only one with this problem, it is perhaps a XIAOMI Bug.
Will test now also with battery below 20%, and then 24h not open.
Let you know as soon as it comes back.

**Comment by redimosi** [comment]
Looks like opening the issue on github did solve the problem. No idea what happened, but since I can not reproduce I close this issue.
