### ISSUE TITLE
Explain  Copyrights given to Ubique

### ISSUE THREAD

**Issue by mvidonne** [DP-3T/dp3t-app-android-ch#196]
Could you please explain what are the [copyrights](https://github.com/DP-3T/dp3t-app-android-ch/commit/650fab16512e81dab91eae5c1bf9af46772ea2b2#diff-5ebe1b20bbb7cecd4a663ff36589583) for  Ubique Innovation and why?  I thought the code was developed with public funds

**Comment by mwellig** [comment]
Tl;dr
Copyright arises automatically and this right cannot be given up. Ubique developed the code, therefore it has the copyright. Note that the code is under a public licence, see the [licence](https://github.com/DP-3T/dp3t-app-android-ch/blob/master/LICENSE)
 
Long Version:
A good summary what Copyright in swiss jurisdiction means can be found here:  [here](https://www.ige.ch/en/protecting-your-ip/copyright/the-basics.html)
 
What is copyright:
> Copyright protects the authors of literary and artistic works. It is the way in which an idea is expressed that is protected, not the idea or concept itself. Copyright protection therefore applies to the form of the work and not its content. For example, Einstein’s essay “The Foundation of the General Theory of Relativity" in the “Annals of Physics” is protected by copyright. The theory of relativity itself, however, may be freely used, just not with the same words as in Einstein’s original text.

> In particular, the source code of computer programs is protected by copyright."

 
Public licencing as means of giving the results to the public (as done with the MPL 2.0 in this project):
> Copyright arises automatically and, in contrast to property law, there is no procedure for simply giving up this right. An author, therefore, does not have any direct possibility of giving a work to the public domain. […] In addition, an author can actively decide to make his work available under an appropriate Creative Commons licence, which is very similar to the public domain, or an equivalent type of public licence."

**Comment by rachyandco** [comment]
@mwellig can you link here the mandate signed between the confederation and Ubique specifically in regards with copyright and licensing of the software, so it is easy for observers to assess that these copyright claims and licensing changes are both legally correct AND valid according the mandate? thanks
