### ISSUE TITLE
Huawei P40 Pro

### ISSUE THREAD

**Issue by Tokolosh** [DP-3T/dp3t-app-android-ch#211]
Does not work on an Android Phone that does not have Google Play Services. So basically useless on any new Huawei Phone thanks to Trump.

Sure, there are ways to get Play Services running on these Phones but an App as important as this should work on these Phones without the need of mentioned Services. - It is a Hassle to get Play Services installed and running on a P40 Pro and even then Push Notifications dont work.

**Comment by simonroesch** [comment]
Most Huawei devices in Switzerland still have Google Play Services installed, only devices that were released after May 16, 2019 are affected by the US ban, see https://support.google.com/android/thread/29434011?hl=en

At the moment devices without Google Play Services are not supported, see also https://github.com/DP-3T/dp3t-app-android-ch/issues/59
To support these new Huawei devices there are two possibilities: either integrating Huawei Contact Shield (covered in https://github.com/DP-3T/dp3t-sdk-android/issues/179) or integrating a completely open source solution as suggested in https://github.com/DP-3T/dp3t-app-android-ch/issues/59 Therefore i will close this issue.
