### ISSUE TITLE
Not up-to-date call to action

### ISSUE THREAD

**Issue by denysvitali** [DP-3T/dp3t-app-android-ch#247]
We have already approached the second wave, I guess it's time to correct the screens to say "Working together to... Prevent a _third_ wave"

![Screenshot_20201029-180658~2](https://user-images.githubusercontent.com/4939519/97607751-b1854700-1a11-11eb-94d4-3f7b3833926c.jpg)

**Comment by simonroesch** [comment]
This has already beend fixed in https://github.com/DP-3T/dp3t-app-android-ch/releases/tag/1.2.0 that will be rolled out over the next days.
