### ISSUE TITLE
App goes in and out of the "restart needed" state

### ISSUE THREAD

**Issue by jeffallen** [DP-3T/dp3t-app-android-ch#29]
I'm using a dev build built from f6b4efb1e on a Huawei PRA-LX1, Android 8.0.

When it says "restart necessary (NSBAE)", I can almost always make it go back to working by bringing up the notifications panel and clicking the notification.

I do not have adb access to this phone, so I can't do better debugging than that.

**Comment by alexandredeleze** [comment]
I have built the commit 84626fd4004a0ee2c7957899b80057d3ec8a2e80 on a Honor 8x, Android 9.1 with Android Studio.
I obtain the NSBAE_bug when I setup the app, close it, remove the cache and clean all datas in Settings/Application/Swiss PT/Storage. When I reopen the app, this error occurs.
![NSBAE_bug](https://user-images.githubusercontent.com/23385049/81422762-b7c9f300-9153-11ea-93c9-cbc16bd95429.jpg)

**Comment by davidperrenoud** [comment]
Could you try the following instructions?
https://dontkillmyapp.com/huawei

**Comment by alexandredeleze** [comment]
I tried your procedure. 4 times over 5 it works perfectly. But the 5th time I had the same error but it disappears after 30 seconds

**Comment by davidperrenoud** [comment]
Good to hear!

Could you paste the result from `adb logcat`?

(I'm not affiliated with the development team by the way.)

**Comment by alexandredeleze** [comment]
So, I used the command ./adb logcat ch.admin.bag.dp3t:v > logcat_swiss_PT.txt and here is the result.
[logcat_swiss_PT.txt](https://github.com/DP-3T/dp3t-app-android-ch/files/4605479/logcat_swiss_PT.txt)

**Comment by simonroesch** [comment]
This issue is resolved with the latest version of the SDK using the Google/Apple Exposure Notification framework.
