### ISSUE TITLE
Notification when Bluetooth and location deactivated 

### ISSUE THREAD

**Issue by alexandredeleze** [DP-3T/dp3t-app-android-ch#37]
I use commit 84626fd4004a0ee2c7957899b80057d3ec8a2e80. The notification in French when the Bluetooth and the location are deactivated is not straightforward, because of the repetition of some information and after "à aucun moment" you have ".,".
![notification](https://user-images.githubusercontent.com/23385049/81424120-be596a00-9155-11ea-8313-4a72ce161411.jpg)

**Comment by davidperrenoud** [comment]
From the README:

> Please note that the app will be available with approved translations in English, German, French and Italian. Pull requests for additional translations currently won't be merged.

I assume that a proper translation will come at a later date.

**Comment by simonroesch** [comment]
We optimized the notification content, please checkout the latest version.
