### ISSUE TITLE
Unexpected error "NSBSE" (SCANNER_ERROR) after serveral days running fine

### ISSUE THREAD

**Issue by zukunft** [DP-3T/dp3t-app-android-ch#40]
Could be, that this error is caused by LineageOS. If yes, this is more a confirmation, that the app error handling is working.
I got an unexpected error "NSBSE" (BLE_SCANNER_ERROR) with a DEV Debug build of 1.0, 0.2.6 on a OnePlus 5T with LineageOS 16.0 from 21. April 2020.

With logcat I just find: 
05-13 17:05:37.610 12916 12932 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=0a138d07-2cf1-4d07-a121-bb2f0704a9f2, tags={ ch.ubique.android.starsdk.SyncWorker } ]

**Comment by simonroesch** [comment]
This issue is resolved with the latest version of the SDK using the Google/Apple Exposure Notification framework!

**Comment by zukunft** [comment]
Now it does not work on LineageOS any more ...

![grafik](https://user-images.githubusercontent.com/5895333/82380828-6e1dba00-9a29-11ea-8b74-147117eb5d25.png)

Is the Google API Open Source, so that it can be included in LineageOS?

**Comment by simonroesch** [comment]
At this moment LineageOS is no longer supported. The Google API is not Open Source but the protocol is Open Source, so it would be possible to create an open source library implementing the Google/Apple protocol and thus be interoperable with it.

**Comment by zukunft** [comment]
Puh, sounds like a little bit of work ... but as you told me before, this was expected. Do you have a link of the protocol?

**Comment by simonroesch** [comment]
Here you go: https://www.google.com/covid19/exposurenotifications/

**Comment by zukunft** [comment]
Thanks.

**Comment by zukunft** [comment]
Looks like the Lineage dev team does not like the GAEN interface too much: https://gitlab.com/LineageOS/issues/android/-/issues/1949 . Maybe it would be easier to use the ex GAEN version and sync the keys on the servers.

**Comment by zukunft** [comment]
Looks to me like at least the error message should be more user friendly, which relates it to  https://github.com/DP-3T/dp3t-app-android-ch/issues/51
