### ISSUE TITLE
Country restriction on Google Play store

### ISSUE THREAD

**Issue by beckm-ethz** [DP-3T/dp3t-app-android-ch#52]
Pilot phase testing is hindered by restriction of Google Play country. Many researchers at EPFL/ETHZ use non-swiss accounts. Countries can be only changed once a year. Also, access to existing Google Play balance is removed by chaging the country. Therefore, a significant number of potential testers will not change their country settings. To include these persons into the pilot phase testing, the country restriction should be removed.

**Comment by simonroesch** [comment]
Thank you for the feedback! We are aware of the issue and are currently checking if we can resolve this.

**Comment by rogerfischer** [comment]
Hi, 
I installed the SwissCovid app, but it looks as if it goes dormant as soon as I use other apps. 
So today for the whole day it says 0s in use. 
Did you already encounter that?

**Comment by gravax** [comment]
I have 2 phone numbers on my phone. A French and a Swiss. Yes... I'm a "frontalier". My phone and Google account are configured in France. How can I install SwissCovid app?

**Comment by beckm-ethz** [comment]
@gravax It's not depending on your phone's numbers, but on the Google Play country defined for your account. Details on changing it can be found there:
https://support.google.com/googleplay/answer/7431675?hl=en
Given that you can change the country only once per year, visitors, cross-border commuters, and tourists are mostly excluded from using this app, unless this restriction is lifted.

**Comment by rachyandco** [comment]
> visitors, cross-border commuters, and tourists are mostly excluded from using this app, unless this restriction is lifted.

Who happens to be very mobile users and **should** be in the scope of the app.

**Comment by treysis** [comment]
> Thank you for the feedback! We are aware of the issue and are currently checking if we can resolve this.

What is the difficulty? It's just a simple check mark in the Google developer console when publishing an app.

**Comment by simonroesch** [comment]
Was not a technical but a legal problem ;-) But the app will be available in all countries for the public launch.

**Comment by treysis** [comment]
Would you mind sharing what the legal problem was?

**Comment by pdehaye** [comment]
Has this been resolved, ahead of the public launch?

**Comment by beckm-ethz** [comment]
To the best of my knowledge, Google so far only allowed one app per country/state. I'm looking forward to check the German Play store for the Swiss app on Thursday.

Given that @simonroesch called it a "legal problem", I would also be curious to learn what legal action convinced Google to give up on geofencing.

**Comment by pdehaye** [comment]
Given that you mention geofencing, do you know if such a problem would occur between say the German and Dutch Play stores? Are there EU regulations that would make this a non-problem outside of Switzerland?

**Comment by rachyandco** [comment]
@simonroesch I would recommend to reopen this issue and keep it open until publicly solved.

**Comment by rachyandco** [comment]
there is also a discussion on the german app github https://github.com/corona-warn-app/cwa-app-android/issues/478

maybe the teams could coordinate to solve the issue?

**Comment by treysis** [comment]
No legal problems with "Immuni" from Italy, apparently. It's available in all country's PlayStore.

@beckm-ethz
Google doesn't require geofencing or restrict the contact tracing apps to certain markets in the PlayStore. The one-app-per-country-policy is accomplished by certificates. Enforcing it only through PlayStore would mean that sideloaded applications could access the API, which is not the case.

**Comment by beckm-ethz** [comment]
I could download the app from the German Google Play store. Well done!
