### ISSUE TITLE
Feature suggestion: Inform user about number of contacts per day

### ISSUE THREAD

**Issue by Dim3nsioneer** [DP-3T/dp3t-app-android-ch#53]
This would be a nice-to-have feature.
As the app stores any contact locally, a feature which would show the number of contacts per day might be useful. The user could improve his/her behavior in terms of social distancing. It could also be a good indicator that it might be a good idea to wear a face mask.
Of course this would also apply to https://github.com/DP-3T/dp3t-app-ios-ch

**Comment by simonroesch** [comment]
Thank you for the feedback! This issue is already tracked on https://github.com/DP-3T/dp3t-ux-screenflows-ch/issues/3

**Comment by jachen** [comment]
Strongly support Dim3nsioneer's suggestion of a feature to show the number of contacts per periode. This would keep users alert to the app presence as well as their physical behavior.
