### ISSUE TITLE
Extension proposal

### ISSUE THREAD

**Issue by havalon** [DP-3T/dp3t-app-android-ch#54]
It should be possible to use a main switch on the main screen, e.g. on top right of the title bar.

This main switch causes three events:
1. on/off of Bluetooth
2. on/off notifications for this app
3. activation/deactivation of the tracing.

The existing "Tracing ON/OFF" switch can thus be omitted.

Reasons:
The app is only used in public area and is only useful there.
Due to the app's continuous notifications, you will feel annoyed very quickly at home.
In addition, the power consumption of Bluetooth, despite BLE, is enormous. (SAMSUNG Galaxy Note S10+)

My experience is that the normal average user does not take the trouble or is overwhelmed,
to tap through the settings each time to turn Bluetooth and the notifications off and on again.

Another security aspect that alone justifies a main switch as described above,
In a public space with Bluetooth activated, it is easy for programmers (hackers) to get around with the appropriate software, manipulate other devices, steal personal data or damage the device.

With my expertise, I never move in public areas with Bluetooth activated.
I only switch it on briefly when I need it and then I make sure that nobody is closer than 10 meters from me.

This means that a main switch in SwissCovid would allow the user to deactivate his tracing app in a bus or train after 15 minutes, after he has assessed his position through the app, and if necessary, switch on again at any time...with one click.

**Comment by simonroesch** [comment]
I moved this issue to https://github.com/DP-3T/dp3t-ux-screenflows-ch/issues/8 as it affects the UX flow for both Android & iOS.
