### ISSUE TITLE
Display number of stored encounters (stats about what is stored in the local database)

### ISSUE THREAD

**Issue by Franklin89** [DP-3T/dp3t-app-android-ch#55]
First off great work 👍 

I was able to download the App from the Play Store yesterday, not sure if this was intended or not.

I like the UI and UX, it is very simple. But what I think would help with transparency is to see the number of datasets stored on my local device. This can also be a little hidden on the info page. For example display the number of current encounters.

This is just an idea and should be simple to be implemented, but it would for sure help me to trust the app more because I can see what it is doing.

**Comment by simonroesch** [comment]
Thanks for your feedback! This issue is already tracked here https://github.com/DP-3T/dp3t-ux-screenflows-ch/issues/3

**Comment by Franklin89** [comment]
@simonroesch Ah thanks, sorry about that. Checked most repositories but not that one 🤑 my bad...

**Comment by simonroesch** [comment]
No problem, we will add it to the Readme shortly to avoid confusion...
