### ISSUE TITLE
SwissCovid app reports 0s of in use

### ISSUE THREAD

**Issue by simonroesch** [DP-3T/dp3t-app-android-ch#57]
Hi, 
I installed the SwissCovid app, but it looks as if it goes dormant as soon as I use other apps. 
So today for the whole day it says 0s in use. 
Did you already encounter that?

_Originally posted by @rogerfischer in https://github.com/DP-3T/dp3t-app-android-ch/issues/52#issuecomment-634070983_

**Comment by LarsBaertschi** [comment]
It runs as a background service, so it doesn't need to be actively in use. Where are you getting the said "0s" in use? Like, what activity overview?

**Comment by simonroesch** [comment]
@rogerfischer can you still reproduce this issue? Can you provide a screenshot of the app usage? Otherwise I would like to close this issue, because I can't reproduce it.

**Comment by rogerfischer** [comment]
@simonroesch 
I had this problems repeatedly or else the app would drain a lot of battery. I deinstalled the app for now. I can retry.

**Comment by simonroesch** [comment]
Please reopen this issue if you can provide more information.
