### ISSUE TITLE
Description could lead to missunderstandings

### ISSUE THREAD

**Issue by Baerbeisser** [DP-3T/dp3t-app-android-ch#58]
> DP-3T is a free-standing effort started at EPFL and ETHZ that produced this protocol and that is implementing it in an open-sourced app and server.

What Server? The App works decentralized.
Uhm, right?

**Comment by simonroesch** [comment]
The server is used to exchange the list of the secret keys of people that were tested positive. See https://github.com/DP-3T/documents for the full documentation of the architecture.
