### ISSUE TITLE
Location / Bluetooth Permissions

### ISSUE THREAD

**Issue by dbrgn** [DP-3T/dp3t-app-android-ch#61]
Right now there is a lot of confusion whether enabling bluetooth and most importantly location is technically required for contact tracing to work.

See this thread for example, with lots of replies and a lot of confusing and contradicting information: https://twitter.com/adfichter/status/1265552302091403266

From what I understand, the DP-3T Android app uses Google's [Exposure Notifications API](https://www.google.com/covid19/exposurenotifications/) to detect exposure and does not in any ways interact with the BLE stack. 

In the [Exposure Notifications API FAQ](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf), it is written:

![image](https://user-images.githubusercontent.com/105168/83012245-6fe41080-a01b-11ea-8dd0-4afb31f419b1.png)

This is reflected in the AndroidManifest:

https://github.com/DP-3T/dp3t-app-android-ch/blob/d87796564efd2cb8fc73e3cb6efb8b75233562a7/app/src/main/AndroidManifest.xml#L14-L15

So the permissions in DP-3T are clear, and no location access will be required. However, the question remains whether the location needs to be enabled at all for SwissCovid to work. The [Android developer documentation](https://t.co/57yYhjzpEY?amp=1) mentions:

![image](https://user-images.githubusercontent.com/105168/83012401-a1f57280-a01b-11ea-943a-c36d291d1f84.png)

So from what I understand, location access is only required to initiate a BLE scan, because that is precisely the way how the location of a user is being estimated. Just having the BLUETOOTH permission does not allow you to determine the location of a user.

So in essence, this boils down to two questions:

1. Do current Google Exposure Notification APIs require that location services are enabled on the device? (I cannot test this since self-compiled versions of the app do not get access to this API, correct?)
2. If this is currently required, is there a technical reason why access to the Exposure Notification API (which happens by whitelisting, if I understand this correctly) does not imply a permission to scan for BLE advertisement frames? (After all, even if the Google Exposure Notification stack does perform scans, the app has no access to them and thus cannot determine the user's location.)

Not needing to enable location services would be a big improvement with regards to user trust.

**Comment by markbosshard** [comment]
Related problem but from an Android user's perspective: The SwissCovid App asks me to turn on Location permissions (and yes Android this makes sense; using Bluetooth permwe are technically traceable, so OK! Even if it will make many users sceptic...).

But: if its not in the manifest the App never asks me for that Permission. (How) can I still enable it for just this app on Android (OxygenOS)? Thanks a lot!

**Comment by simonroesch** [comment]
The SwissCovid app uses the [ExposureNotification framework provided by Google](https://www.google.com/covid19/exposurenotifications/). This is integrated as part of the Google Play Services and only whitelisted public health authority apps get access to the framework. The whole Bluetooth advertisement and scanning is done by the Google Play Services and therefore our app does not require the BLUETOOTH_ADMIN or ACCESS_FINE_LOCATION permission. But unfortunately it is a restriction of the Android system that BLE scanning can only be performed, when the global device location services switch is turned on. This is intended behaviour on Android (see https://issuetracker.google.com/issues/37065090) but extremly confusing for this usecase.

**Comment by markbosshard** [comment]
How to enable this permission during battery saver? Or you are saying we cant use SwissCovid in battery saver at all?

**Comment by simonroesch** [comment]
You have to configure battery saver in such a way that it does not disable location services, otherwise it will not be possible to register any contacts.

**Comment by markbosshard** [comment]
1) a high number on Android uses the battery saver almost permanently. Even as a techie I was no table how to set this exception for location within 5mins. Definitely take this into your tutorial!!!

2) make sure not to enable my whole GPS module when drafting this battery saver exception. Constant GPS draws a lot of battery and I do not think we need to put this burden on uswrs just to run a Bluetooth tracing app.

**Comment by dbrgn** [comment]
Thank you @simonroesch for the explanation and the link to the Google issue tracker. The technical choice on their end makes no sense to me, but I see that there's nothing you can do about it. Too bad...

**Comment by treysis** [comment]
@dbrgn Exactly. In Android 11 it might be possible, but with just PlayServices Google cannot circumvent the requirement.

However, you could reject the location permission for every app except PlayServices. Unfortunately, also PlayServices uses GPS from time to time, and this cannot be disabled starting with Android 9.

I think Google should implement a user-controllable switch inside PlayServices which disables location access by PlayServices except for contact tracing.

**Comment by max-wittig** [comment]
I'm just wondering why the German version of the tracing app doesn't require the app to run in the background. Repo at: https://github.com/corona-warn-app/cwa-app-android

**Comment by treysis** [comment]
Puh, good question. But I noticed the same. It only gets updated when I actively open it. Android seems to kill it in the background.
