### ISSUE TITLE
Covidcode field slightly too large in inform screen

### ISSUE THREAD

**Issue by DidierGenard** [DP-3T/dp3t-app-android-ch#9]
Hi DP-3T team!

Nice work for a first draft version!
I found the following issue on my phone: the left and right sides of the input field in the fragment_inform screen are slightly cut (the left border is missing on the first digit and the right border is missing on the last digit). See attached screenshots.

Device: Motorola Moto G9
Android Version 9
Display size: 1080x2160

![Screenshot_20200504-122824](https://user-images.githubusercontent.com/64638163/80957795-2c272e00-8e04-11ea-88d7-f985eaf6b096.png)
![Screenshot_20200504-122849](https://user-images.githubusercontent.com/64638163/80957803-2fbab500-8e04-11ea-84eb-ecb6832c7e78.png)

**Comment by benz-ubique** [comment]
Fixed: The fields are distributed over two lines now
