### ISSUE TITLE
App unable to function properly after switching to Android 11 beta

### ISSUE THREAD

**Issue by ogay** [DP-3T/dp3t-app-android-ch#94]
Hi DP-3T,

after switching to Android 11 beta 1, the app now constantly sends this Android notification:
_"App currently unable to function properly.
It has not been possible to synchronise reports for some time. Please check that your device is connected to the internet. (ASST502)"_

Internet works fine, issue occurs no matter if 4G or Wi-Fi is used.
Uninstalling & reinstalling the app or restarting the device does not help.

App version: version 1.0.3-pilot, 0.5.6
Android version: Android 11 beta 1, build RPB1.200504.018
HW: Pixel 3

**Comment by simonroesch** [comment]
This error was not due to your update to Android 11 but was caused due to some planned backend maintenance yesterday. Please verify that the app is now working correctly.

**Comment by ogay** [comment]
> This error was not due to your update to Android 11 but was caused due to some planned backend maintenance yesterday. Please verify that the app is now working correctly.

App is now working correctly.
